console.log('This is tut11');
let a = window.document;
// // a = prompt('This will destroy your computer. Type your name.');
// a = confirm('You want to delete this page.');
// a = window.innerHeight;
// a = window.innerWidth;
// a = scrollX;
// a = scrollY;
a = location;
// a = location.reload();
// a = location.href;
// a = location.href = 'facebook.com';
// a = location.href = '//facebook.com';
// a = location.toString();
console.log(a);